
services:
  app:
    container_name: pretix_app
    image: pretix/standalone:stable
    restart: always
    depends_on:
      - database
      - cache
    volumes:
      - pretix_data:/data
    environment:
      # Basic settings
      - PRETIX_INSTANCE_NAME=My Pretix Installation
      - PRETIX_URL=https://v1.tickets.kulturleben-berlin.de
      - PRETIX_CURRENCY=EUR
      - PRETIX_DATADIR=/data
      - PRETIX_TRUST_X_FORWARDED_FOR=on
      - PRETIX_TRUST_X_FORWARDED_PROTO=on
      - PRETIX_REGISTRATION=off
      
      # Locale settings
      - PRETIX_DEFAULT_LOCALE=de
      - PRETIX_TIMEZONE=Europe/Berlin
      
      # Database settings
      - PRETIX_DATABASE_BACKEND=postgresql
      - PRETIX_DATABASE_NAME=pretix
      - PRETIX_DATABASE_USER=pretix
      - PRETIX_DATABASE_PASSWORD=pretix
      - PRETIX_DATABASE_HOST=database
      
      # Redis settings
      - PRETIX_REDIS_LOCATION=redis://cache/0
      - PRETIX_REDIS_SESSIONS=true
      
      # Celery settings
      - PRETIX_CELERY_BACKEND=redis://cache/1
      - PRETIX_CELERY_BROKER=redis://cache/2
      
      # Celery environment variables
      - CELERY_BROKER_URL=redis://cache:6379/2
      - CELERY_RESULT_BACKEND=redis://cache:6379/1
    command: ["web"]
    networks:
      - backend

  worker:
    container_name: pretix_worker
    image: pretix/standalone:stable
    restart: always
    depends_on:
      - database
      - cache
    volumes:
      - pretix_data:/data
    environment:
      # Basic settings
      - PRETIX_INSTANCE_NAME=My Pretix Installation
      - PRETIX_URL=https://v1.tickets.kulturleben-berlin.de
      - PRETIX_CURRENCY=EUR
      - PRETIX_DATADIR=/data
      - PRETIX_TRUST_X_FORWARDED_FOR=on
      - PRETIX_TRUST_X_FORWARDED_PROTO=on
      - PRETIX_REGISTRATION=off
      
      # Locale settings
      - PRETIX_DEFAULT_LOCALE=de
      - PRETIX_TIMEZONE=Europe/Berlin
      
      # Database settings
      - PRETIX_DATABASE_BACKEND=postgresql
      - PRETIX_DATABASE_NAME=pretix
      - PRETIX_DATABASE_USER=pretix
      - PRETIX_DATABASE_PASSWORD=pretix
      - PRETIX_DATABASE_HOST=database
      
      # Redis settings
      - PRETIX_REDIS_LOCATION=redis://cache/0
      - PRETIX_REDIS_SESSIONS=true
      
      # Celery settings
      - PRETIX_CELERY_BACKEND=redis://cache/1
      - PRETIX_CELERY_BROKER=redis://cache/2
      
      # Celery environment variables
      - CELERY_BROKER_URL=redis://cache:6379/2
      - CELERY_RESULT_BACKEND=redis://cache:6379/1
    command: ["worker"]
    networks:
      - backend

  database:
    image: postgres:17-alpine3.22
    container_name: database
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  cache:
    image: redis:alpine3.22
    container_name: redis
    restart: always
    networks:
      - backend

volumes:
  postgres_data:
    driver: local
  pretix_data:
    driver: local

networks:
  backend:
    driver: bridge